# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Indietool < Formula
  desc "An all-in-one tool for unified infrastructure management"
  homepage "https://github.com/indietool/cli"
  version "0.0.7"
  license "Apache 2"

  depends_on "ca-certificates" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indietool/cli/releases/download/v0.0.7/indietool-0.0.7-darwin-amd64.tar.gz"
      sha256 "03ef5f462759dc7213c09d79f0256d03c947662643b8671163234a29395a3f24"

      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indietool/cli/releases/download/v0.0.7/indietool-0.0.7-darwin-arm64.tar.gz"
      sha256 "9f8aebb82b430d52376beaa0d6e7b80918258f0c98326e884b9f42028b94609c"

      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.7/indietool-0.0.7-linux-amd64.tar.gz"
      sha256 "a642e3030e656ef9f9d992b3011f0b6643ae028bfde523ddc4cc6362594af3f0"
      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.7/indietool-0.0.7-linux-arm64.tar.gz"
      sha256 "8c298cac2707d1c1e58029d30dd8c24682dd7cc42116137960d6e106a91cd30a"
      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  test do
    system "#{bin}/indietool", "--version"
  end
end
