# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Indietool < Formula
  desc "An all-in-one tool for unified infrastructure management"
  homepage "https://github.com/indietool/cli"
  version "0.0.5"
  license "Apache 2"

  depends_on "ca-certificates" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indietool/cli/releases/download/v0.0.5/indietool-0.0.5-darwin-amd64.tar.gz"
      sha256 "b1d3d1119359ac5d29d28a00cb067f2e33e36a6b5a2ad0c3d5cc27e7e02be93b"

      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indietool/cli/releases/download/v0.0.5/indietool-0.0.5-darwin-arm64.tar.gz"
      sha256 "13caf0684dd3e71291674a8db3bec2ad0570064832e599bb2c64b5d710389f8d"

      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.5/indietool-0.0.5-linux-amd64.tar.gz"
      sha256 "2d87a92c0807b80af7235273d9e1ee7d4f53e25cfabdede11ab1ce6e5d78b50e"
      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.5/indietool-0.0.5-linux-arm64.tar.gz"
      sha256 "74c6d7f7a26f4eb11fb26c8e64ae5397740425d023099cb4f30ba8ad65ffe925"
      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  test do
    system "#{bin}/indietool", "--version"
  end
end
