# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Indietool < Formula
  desc "An all-in-one tool for unified infrastructure management"
  homepage "https://github.com/indietool/cli"
  version "0.0.4"
  license "Apache 2"

  depends_on "ca-certificates" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indietool/cli/releases/download/v0.0.4/indietool-0.0.4-darwin-amd64.tar.gz"
      sha256 "2dd357370d0216decaae24624bfce7c506003764a09e2865ab72e2127214049c"

      def install
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indietool/cli/releases/download/v0.0.4/indietool-0.0.4-darwin-arm64.tar.gz"
      sha256 "69aadc3be7df471c7cb33a2b4e99292b0001ba5459270fb1f2944bd1e8d04398"

      def install
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.4/indietool-0.0.4-linux-amd64.tar.gz"
      sha256 "8e83136e461397988b7e1d75b9494b0d0fc8f38fb1763811fa4b37618828f678"
      def install
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.4/indietool-0.0.4-linux-arm64.tar.gz"
      sha256 "a5593456c55956355d642eedaa3a1c7b63efa7d958514dd15ca0df030c2cf942"
      def install
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  test do
    system "#{bin}/indietool", "--version"
  end
end
