# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Indietool < Formula
  desc "An all-in-one tool for unified infrastructure management"
  homepage "https://github.com/indietool/cli"
  version "0.0.9"
  license "Apache-2.0"

  depends_on "ca-certificates" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indietool/cli/releases/download/v0.0.9/indietool-0.0.9-darwin-amd64.tar.gz"
      sha256 "fa6f72a888d41f1578e02722240fb20153a46cd9c6133442b2221d4100d69216"

      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indietool/cli/releases/download/v0.0.9/indietool-0.0.9-darwin-arm64.tar.gz"
      sha256 "2ea91d66fae61fa966bce4dbe6539f35abc1aa24524f464db17e0094db8e65d2"

      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.9/indietool-0.0.9-linux-amd64.tar.gz"
      sha256 "e341b9f4614a3231cb6800097d87321fa97b42526afebe4c42bb73f4849a8cc8"
      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indietool/cli/releases/download/v0.0.9/indietool-0.0.9-linux-arm64.tar.gz"
      sha256 "86c4c11d56aafcebae24689a15fa154eebc40129fb7eecd4cc0a349ea9daa7ac"
      define_method(:install) do
        bin.install "indietool"

        # Generate shell completions
        generate_completions_from_executable(bin/"indietool", "completion")
      end
    end
  end

  test do
    system "#{bin}/indietool", "--version"
  end
end
